# Generated by Django 3.2.23 on 2023-11-16 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0052_fix_interface_redundancy_group_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='generic-attachments')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
