# Generated by Django 3.2.23 on 2023-11-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0052_fix_interface_redundancy_group_created'),
        ('nautobot_attachment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Attachment',
        ),
    ]
