# Generated by Django 3.2.23 on 2023-12-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_attachment', '0004_attachment_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='location',
            new_name='parent',
        ),
    ]
